# Generated by Django 2.2.7 on 2019-11-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_auto_20191109_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='display_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.TextField(),
        ),
    ]
