# Generated by Django 2.2.8 on 2020-01-08 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0007_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
