# Generated by Django 2.2.8 on 2020-01-25 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0008_auto_20200108_0750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='subscriptions',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='children_array',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='path',
        ),
    ]
